# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build_and_push_image:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout Code from repository
        uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Login to docker hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Runs a set of commands using the runners shell
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: sourav15/user-dev-${{ github.run_number }}

  modify_image:
    needs: build_and_push_image
    runs-on: ubuntu-latest
    steps:
      - name: Changing the deployment of git repo
        uses: actions/checkout@v4
        with:
          repository: https://github.com/sourav15/argo-cd-manifest.git
          token: ${{ secrets.GIT_TOKEN }}
          ref: branch-to-pull

      - name: modify the image
        run: |
          git config user.email ${{ secrets.EMAIL }}
          git config user.name ${{ secrets.NAME }}
          echo “Working Directory: $(pwd)”
          sed -i 's/user-dev-[0-9]\{1,\}/user-dev-${{ github.run_number }}/' user-deployment.yaml
          git add user-deployment.yaml
          git commit -m "Update image tag by Github Actions Job change manifest: ${{ github.run_number }}"
          git push origin master
